services:
  openwebui:
    container_name: openwebui
    cpus: "1.0"
    env_file:
      - .env
    image: dyrnq/open-webui:v0.3.27-cuda
    mem_limit: 4g
    networks:
      - ai-net
    pids_limit: 1000
    ports:
      - "3000:8080"
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./data:/app/backend/data

networks:
  ai-net:
    external: true

volumes:
  openwebui:
